#!/bin/bash

#### Constants ####

TEST_IMPORT_LIST=()

TEST_FILE="test.sh"

#### import ####


# import django
DJANGO_FOLDER_PATH="experiments/import/django/"
DJANGO_APP_NAME="django"
DJANGO_NUM_TRAILS=1

# import flask
FLASK_FOLDER_PATH="experiments/import/flask/"
FLASK_APP_NAME="flask"
FLASK_NUM_TRAILS=1

# import jinja2
JINJA2_FOLDER_PATH="experiments/import/jinja2/"
JINJA2_APP_NAME="jinja2"
JINJA2_NUM_TRAILS=1

# import matplotlib
MATPLOTLIB_FOLDER_PATH="experiments/import/matplotlib/"
MATPLOTLIB_APP_NAME="matplotlib"
MATPLOTLIB_NUM_TRAILS=1

# import numpy
NUMPY_FOLDER_PATH="experiments/import/numpy/"
NUMPY_APP_NAME="numpy"
NUMPY_NUM_TRAILS=1

# import pip
PIP_FOLDER_PATH="experiments/import/pip/"
PIP_APP_NAME="pip"
PIP_NUM_TRAILS=1

# import requests
REQUESTS_FOLDER_PATH="experiments/import/requests/"
REQUESTS_APP_NAME="requests"
REQUESTS_NUM_TRAILS=1

# import setuptools
SETUPTOOLS_FOLDER_PATH="experiments/import/setuptools/"
SETUPTOOLS_APP_NAME="setuptools"
SETUPTOOLS_NUM_TRAILS=1

# import sqlalchemy
SQLALCHEMY_FOLDER_PATH="experiments/import/sqlalchemy/"
SQLALCHEMY_APP_NAME="sqlalchemy"
SQLALCHEMY_NUM_TRAILS=1

# import Standard
STANDARD_FOLDER_PATH="experiments/import/Standard/"
STANDARD_APP_NAME="requests"
STANDARD_NUM_TRAILS=1

# import werkzeug
WERKZEUG_FOLDER_PATH="experiments/import/werkzeug/"
WERKZEUG_APP_NAME="werkzeug"
WERKZEUG_NUM_TRAILS=1

# Generate list of tests
gen_import_cmds() {
  RUNTIME=$1
  
  # import django
  TEST_IMPORT_LIST+=("$DJANGO_FOLDER_PATH$TEST_FILE $DJANGO_FOLDER_PATH $DJANGO_APP_NAME $RUNTIME $DJANGO_NUM_TRAILS")
  # import flask
  TEST_IMPORT_LIST+=("$FLASK_FOLDER_PATH$TEST_FILE $FLASK_FOLDER_PATH $FLASK_APP_NAME $RUNTIME $FLASK_NUM_TRAILS")
  # import jinja2
  TEST_IMPORT_LIST+=("$JINJA2_FOLDER_PATH$TEST_FILE $JINJA2_FOLDER_PATH $JINJA2_APP_NAME $RUNTIME $JINJA2_NUM_TRAILS")
  # import matplotlib
  TEST_IMPORT_LIST+=("$MATPLOTLIB_FOLDER_PATH$TEST_FILE $MATPLOTLIB_FOLDER_PATH $MATPLOTLIB_APP_NAME $RUNTIME $MATPLOTLIB_NUM_TRAILS")
  # import numpy
  TEST_IMPORT_LIST+=("$NUMPY_FOLDER_PATH$TEST_FILE $NUMPY_FOLDER_PATH $NUMPY_APP_NAME $RUNTIME $NUMPY_NUM_TRAILS")
  # import pip
  TEST_IMPORT_LIST+=("$PIP_FOLDER_PATH$TEST_FILE $PIP_FOLDER_PATH $PIP_APP_NAME $RUNTIME $PIP_NUM_TRAILS")
  # import requests
  TEST_IMPORT_LIST+=("$REQUESTS_FOLDER_PATH$TEST_FILE $REQUESTS_FOLDER_PATH $REQUESTS_APP_NAME $RUNTIME $REQUESTS_NUM_TRAILS")
  # import setuptools
  TEST_IMPORT_LIST+=("$SETUPTOOLS_FOLDER_PATH$TEST_FILE $SETUPTOOLS_FOLDER_PATH $SETUPTOOLS_APP_NAME $RUNTIME $SETUPTOOLS_NUM_TRAILS")
  # import sqlalchemy
  TEST_IMPORT_LIST+=("$SQLALCHEMY_FOLDER_PATH$TEST_FILE $SQLALCHEMY_FOLDER_PATH $SQLALCHEMY_APP_NAME $RUNTIME $SQLALCHEMY_NUM_TRAILS")
  # import Standard
  TEST_IMPORT_LIST+=("$STANDARD_FOLDER_PATH$TEST_FILE $STANDARD_FOLDER_PATH $STANDARD_APP_NAME $RUNTIME $STANDARD_NUM_TRAILS")
  # import werkzeug
  TEST_IMPORT_LIST+=("$WERKZEUG_FOLDER_PATH$TEST_FILE $WERKZEUG_FOLDER_PATH $WERKZEUG_APP_NAME $RUNTIME $WERKZEUG_NUM_TRAILS")

}
