#!/bin/bash

#### Constants ####

TEST_LIFECYCLE_LIST=()

TEST_FILE="test.sh"

#### lifecycle ####
USAGE_CMD="sh test.sh <FOLDER_PATH> <APP_NAME> <RUNTIME> <NUM_THREADs> <NUM_TRIALS> <RUNTIME> <NUM_SPINUPS_PER_THREAD>"

# thread_spinup_throughput
THREAD_FOLDER_PATH="experiments/lifecycle/thread_spinup_throughput/"
THREAD_APP_NAME="spinup"
THREAD_SPINUP_NUM_THREADS=1
THREAD_SPINUP_NUM_TRIALS=1
THREAD_SPINUP_NUM_SPINUPS_PER_THREAD=1


	# Generate list of tests
generate_cmds() {
  	RUNTIME=$1
	
	if [[ $RUNTIME == "runsc" ]]; then
	
		# Thread_throughput
		TEST_LIFECYCLE_LIST+=("$THREAD_FOLDER_PATH$TEST_FILE $THREAD_FOLDER_PATH $THREAD_APP_NAME $RUNTIME $THREAD_SPINUP_NUM_THREADS $THREAD_SPINUP_NUM_TRIALS "kvm" $THREAD_SPINUP_NUM_SPINUPS_PER_THREAD")
		TEST_LIFECYCLE_LIST+=("$THREAD_FOLDER_PATH$TEST_FILE $THREAD_FOLDER_PATH $THREAD_APP_NAME $RUNTIME $THREAD_SPINUP_NUM_THREADS $THREAD_SPINUP_NUM_TRIALS "ptrace" $THREAD_SPINUP_NUM_SPINUPS_PER_THREAD")
	else
		TEST_LIFECYCLE_LIST+=("$THREAD_FOLDER_PATH$TEST_FILE $THREAD_FOLDER_PATH $THREAD_APP_NAME $RUNTIME $THREAD_SPINUP_NUM_THREADS $THREAD_SPINUP_NUM_TRIALS $RUNTIME $THREAD_SPINUP_NUM_SPINUPS_PER_THREAD")
	fi
}
